steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    id: Build Node app
    entrypoint: 'pack'
    args: ['build', '--builder=gcr.io/buildpacks/builder', '--publish', 'gcr.io/$PROJECT_ID/web-data-app:$COMMIT_SHA']
  #- name: bash
  #  script: |
  #    #!/usr/bin/env bash
  #    pwd
  #    mkdir changelog
  #    ls
  #    cp db_config/* changelog
  #    cd changelog
  #    ls
  - name: gcr.io/cloud-builders/gsutil
    args:
      - cp
      - 'gs://liquibase-jars/*'
      - /workspace/lib
    dir: lib
    id: Get Liquibase Jar files
  #- name: bash
  #  id: Prove that files copied correctly
  #  script: |
  #    #!/usr/bin/env bash
  #    ls
  #    echo 'all folders listed'
  #    cd lib
  #    ls
  #- name: gcr.io/cloud-builders/gsutil
  #  args:
  #    - cp
  #    - 'gs://liquibase-configs/*.*'
  #    - /workspace/changelog
  #  dir: changelog
  #  id: Get Liquibase config files
  - name: gcr.io/cloud-builders/docker
    args:
      - run
      - '--network=cloudbuild'
      - '--rm'
      - '--volume'
      - '/workspace/db_config:/liquibase/changelog'
      - '--volume'
      - '/workspace/lib:/liquibase/lib'
      - liquibase/liquibase
      - '--include-system-classpath=true'
      - '--changeLogFile=changelog/changelog.yaml'
      - '--defaultsFile=/liquibase/changelog/liquibase.properties'
      - update
    id: Update BigQuery
