steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    id: Build Node app
    entrypoint: 'pack'
    args: ['build', '--builder=gcr.io/buildpacks/builder', '--publish', 'gcr.io/$PROJECT_ID/web-data-app:$COMMIT_SHA']
  - name: bash
    script: |
      #!/usr/bin/env bash
      pwd
      ls
  #- name: gcr.io/cloud-builders/gsutil
  #  args:
  #    - cp
  #    - 'gs://liquibase-jars/*.jar'
  #    - /workspace/lib
  #  dir: lib
  #  id: Get Liquibase Jar files
  #- name: gcr.io/cloud-builders/gsutil
  #  args:
  #    - cp
  #    - 'gs://liquibase-configs/*.*'
  #    - /workspace/changelog
  #  dir: changelog
  #  id: Get Liquibase config files
  #- name: gcr.io/cloud-builders/docker
  #  args:
  #    - run
  #    - '--network=cloudbuild'
  #    - '--rm'
  #    - '--volume'
  #    - '/workspace/changelog:/liquibase/changelog'
  #    - '--volume'
  #    - '/workspace/lib:/liquibase/lib'
  #    - liquibase/liquibase
  #    - '--include-system-classpath=true'
  #    - '--changeLogFile=changelog/changelog.yaml'
  #    - '--defaultsFile=/liquibase/changelog/liquibase.properties'
  #    - update
  #  id: Update BQ
