apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-data-app-deployment
spec:
  selector:
    matchLabels:
      app: web-data-app
  template:
    metadata:
      labels:
        app: web-data-app
    spec:
      containers:
      - name: web-data-app
        image: gcr.io/seroter-project-base/web-data-app
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
